"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  Tooltip,
  CartesianGrid,
  ResponsiveContainer,
  BarChart,
  Bar,
} from "recharts";

export default function AdminClientDetailsPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const [clientId, setClientId] = useState("");
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  const loadClient = async (id: string) => {
    try {
      setLoading(true);

      const res = await fetch(`/api/admin/clients/${id}`);
      const json = await res.json();

      if (json.success) {
        setData(json.data);
      } else {
        setData(null);
      }
    } catch (error) {
      console.log("CLIENT DETAIL LOAD ERROR:", error);
      setData(null);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    params.then((p) => {
      setClientId(p.id);
      loadClient(p.id);
    });
  }, [params]);

  const downloadReport = () => {
    if (!data) return;

    const profile = data.profile;
    const latest = data.latestMetric;
    const metrics = data.metrics || [];
    const photos = data.photos || [];

    const metricsText =
      metrics.length === 0
        ? "No metrics available."
        : metrics
            .map((item: any, index: number) => {
              return `
Entry #${index + 1}
Date: ${item.date}
Weight: ${item.weight} kg
Height: ${item.height} cm
BMI: ${item.bmi}
Calories: ${item.calories} kcal
Goal: ${item.goal}
Activity: ${item.activity}
------------------------------`;
            })
            .join("\n");

    const report = `
ATHLETEOS ADMIN CLIENT REPORT
=============================

Client Information
------------------
Name: ${profile?.name || "No profile"}
Email: ${profile?.email || data.user.email}
User ID: ${data.user.id}
Goal: ${profile?.goal || "Not set"}
Activity: ${profile?.activity || "Not set"}
Age: ${profile?.age || "Not set"}

Latest Metrics
--------------
Weight: ${latest ? latest.weight + " kg" : "Not set"}
Height: ${latest ? latest.height + " cm" : "Not set"}
BMI: ${latest ? latest.bmi : "Not set"}
Calories: ${latest ? latest.calories + " kcal" : "Not set"}
Date: ${latest ? latest.date : "Not set"}

Stats
-----
Entries: ${data.stats.entries}
Photos: ${photos.length}

Metrics History
---------------
${metricsText}

Generated by AthleteOS Admin Dashboard
`;

    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);

    const a = document.createElement("a");
    a.href = url;
    a.download = `client-report-${data.user.id}.txt`;
    a.click();

    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="text-white">
        <div className="bg-gray-900 p-6 rounded-xl animate-pulse">
          <div className="h-5 bg-gray-700 rounded w-1/3 mb-4"></div>
          <div className="h-3 bg-gray-700 rounded w-full mb-2"></div>
          <div className="h-3 bg-gray-700 rounded w-2/3"></div>
        </div>
      </div>
    );
  }

  if (!data) {
    return (
      <div className="text-white">
        <Link
          href="/dashboard/clients"
          className="text-blue-400 hover:text-blue-300"
        >
          ← Back to Clients
        </Link>

        <div className="bg-gray-900 border border-gray-800 p-8 rounded-2xl mt-6">
          Client not found.
        </div>
      </div>
    );
  }

  const profile = data.profile;
  const latest = data.latestMetric;
  const metrics = data.metrics || [];
  const photos = data.photos || [];

  return (
    <div className="text-white space-y-6">

      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">

        <div>
          <Link
            href="/dashboard/clients"
            className="text-blue-400 hover:text-blue-300"
          >
            ← Back to Clients
          </Link>

          <h1 className="text-3xl font-bold mt-3">
            {profile?.name || "Client Details"}
          </h1>

          <p className="text-gray-400">
            {profile?.email || data.user.email}
          </p>
        </div>

        <div className="flex gap-3">

          <button
            onClick={() => clientId && loadClient(clientId)}
            className="bg-blue-500 hover:bg-blue-400 px-4 py-2 rounded-xl transition"
          >
            Refresh
          </button>

          <button
            onClick={downloadReport}
            className="bg-green-500 hover:bg-green-400 text-black px-4 py-2 rounded-xl transition"
          >
            Download Report
          </button>

        </div>

      </div>

      <div className="grid md:grid-cols-4 gap-4">

        <div className="bg-gray-900 border border-gray-800 p-5 rounded-2xl">
          <p className="text-gray-400 text-sm">Goal</p>
          <h3 className="text-lg font-bold text-green-400">
            {profile?.goal || latest?.goal || "Not set"}
          </h3>
        </div>

        <div className="bg-gray-900 border border-gray-800 p-5 rounded-2xl">
          <p className="text-gray-400 text-sm">Activity</p>
          <h3 className="text-lg font-bold text-blue-400">
            {profile?.activity || latest?.activity || "Not set"}
          </h3>
        </div>

        <div className="bg-gray-900 border border-gray-800 p-5 rounded-2xl">
          <p className="text-gray-400 text-sm">Entries</p>
          <h3 className="text-lg font-bold">
            {data.stats.entries}
          </h3>
        </div>

        <div className="bg-gray-900 border border-gray-800 p-5 rounded-2xl">
          <p className="text-gray-400 text-sm">Photos</p>
          <h3 className="text-lg font-bold">
            {data.stats.photos}
          </h3>
        </div>

      </div>

      {metrics.length > 0 && (
        <div className="grid lg:grid-cols-2 gap-6">

          <div className="bg-gray-900 border border-gray-800 p-6 rounded-2xl">
            <h2 className="text-xl font-bold mb-4">
              Weight Progress
            </h2>

            <div className="h-72">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={metrics}>
                  <CartesianGrid stroke="#334155" />
                  <XAxis dataKey="date" />
                  <YAxis />
                  <Tooltip />
                  <Line
                    type="monotone"
                    dataKey="weight"
                    stroke="#22c55e"
                    strokeWidth={3}
                  />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </div>

          <div className="bg-gray-900 border border-gray-800 p-6 rounded-2xl">
            <h2 className="text-xl font-bold mb-4">
              Calories
            </h2>

            <div className="h-72">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={metrics}>
                  <CartesianGrid stroke="#334155" />
                  <XAxis dataKey="date" />
                  <YAxis />
                  <Tooltip />
                  <Bar
                    dataKey="calories"
                    fill="#3b82f6"
                    radius={[8, 8, 0, 0]}
                  />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>

        </div>
      )}

      <div className="bg-gray-900 border border-gray-800 p-6 rounded-2xl">

        <h2 className="text-xl font-bold mb-4">
          Latest Metrics
        </h2>

        {latest ? (
          <div className="grid md:grid-cols-5 gap-4">

            <div className="bg-gray-800 p-4 rounded-xl">
              <p className="text-xs text-gray-400">Weight</p>
              <h3 className="text-lg font-bold">{latest.weight}kg</h3>
            </div>

            <div className="bg-gray-800 p-4 rounded-xl">
              <p className="text-xs text-gray-400">Height</p>
              <h3 className="text-lg font-bold">{latest.height}cm</h3>
            </div>

            <div className="bg-gray-800 p-4 rounded-xl">
              <p className="text-xs text-gray-400">BMI</p>
              <h3 className="text-lg font-bold text-green-400">{latest.bmi}</h3>
            </div>

            <div className="bg-gray-800 p-4 rounded-xl">
              <p className="text-xs text-gray-400">Calories</p>
              <h3 className="text-lg font-bold">{latest.calories}</h3>
            </div>

            <div className="bg-gray-800 p-4 rounded-xl">
              <p className="text-xs text-gray-400">Date</p>
              <h3 className="text-lg font-bold">{latest.date}</h3>
            </div>

          </div>
        ) : (
          <p className="text-gray-400">No metrics yet.</p>
        )}

      </div>

      <div className="bg-gray-900 border border-gray-800 p-6 rounded-2xl">

        <h2 className="text-xl font-bold mb-4">
          Metrics History
        </h2>

        {metrics.length === 0 ? (
          <div className="border border-dashed border-gray-700 rounded-xl p-8 text-center text-gray-500">
            No history available.
          </div>
        ) : (
          <div className="overflow-x-auto">

            <table className="w-full text-left">

              <thead className="text-gray-400 text-sm">
                <tr className="border-b border-gray-800">
                  <th className="py-3">Date</th>
                  <th className="py-3">Weight</th>
                  <th className="py-3">Height</th>
                  <th className="py-3">BMI</th>
                  <th className="py-3">Calories</th>
                  <th className="py-3">Goal</th>
                </tr>
              </thead>

              <tbody>
                {metrics.map((item: any) => (
                  <tr
                    key={item._id}
                    className="border-b border-gray-800 hover:bg-gray-800/50 transition"
                  >
                    <td className="py-3">{item.date}</td>
                    <td className="py-3">{item.weight}kg</td>
                    <td className="py-3">{item.height}cm</td>
                    <td className="py-3">{item.bmi}</td>
                    <td className="py-3">{item.calories} kcal</td>
                    <td className="py-3">{item.goal}</td>
                  </tr>
                ))}
              </tbody>

            </table>

          </div>
        )}

      </div>

      <div className="bg-gray-900 border border-gray-800 p-6 rounded-2xl">

        <h2 className="text-xl font-bold mb-4">
          Progress Photos
        </h2>

        {photos.length === 0 ? (
          <div className="border border-dashed border-gray-700 rounded-xl p-8 text-center text-gray-500">
            No photos uploaded yet.
          </div>
        ) : (
          <div className="grid md:grid-cols-3 gap-4">

            {photos.map((photo: any) => (
              <div
                key={photo._id}
                className="bg-gray-800 rounded-2xl overflow-hidden border border-gray-700"
              >

                <img
                  src={photo.image}
                  alt="Progress"
                  className="w-full h-56 object-cover"
                />

                <div className="p-4 space-y-2">

                  <div className="flex justify-between items-center">
                    <p className="text-sm text-gray-400">{photo.date}</p>

                    <span className="bg-green-500/20 text-green-400 px-3 py-1 rounded-full text-sm">
                      {photo.score}/100
                    </span>
                  </div>

                  <p className="text-sm">
                    Goal: <span className="text-blue-400">{photo.goal}</span>
                  </p>

                  <p className="text-sm text-gray-300">
                    {photo.feedback}
                  </p>

                </div>

              </div>
            ))}

          </div>
        )}

      </div>

    </div>
  );
}