"use client";

import toast from "react-hot-toast";

export default function QuickActions() {

  const resetProgress = () => {
    const confirmed = window.confirm(
      "Are you sure you want to reset your progress goals?"
    );

    if (!confirmed) return;

    localStorage.removeItem("clientStartWeight");
    localStorage.removeItem("clientGoalWeight");

    window.dispatchEvent(new Event("metricsUpdated"));

    toast.success("Progress goals reset successfully");
  };

  const clearHistory = async () => {
    const confirmed = window.confirm(
      "Are you sure you want to clear all measurement history from MongoDB?"
    );

    if (!confirmed) return;

    const userId = localStorage.getItem("userId");

    if (!userId) {
      toast.error("User not connected");
      return;
    }

    await fetch(`/api/client/metrics?userId=${userId}`, {
      method: "DELETE",
    });

    localStorage.removeItem("clientMetricsHistory");

    window.dispatchEvent(new Event("metricsUpdated"));

    toast.success("History cleared from MongoDB");
  };

  const clearPhotos = async () => {
    const confirmed = window.confirm(
      "Are you sure you want to clear all progress photos from MongoDB?"
    );

    if (!confirmed) return;

    const userId = localStorage.getItem("userId");

    if (!userId) {
      toast.error("User not connected");
      return;
    }

    await fetch(`/api/client/photos?userId=${userId}`, {
      method: "DELETE",
    });

    toast.success("Progress photos cleared from MongoDB");

    setTimeout(() => {
      window.location.reload();
    }, 700);
  };

  const clearAll = async () => {
    const confirmed = window.confirm(
      "This will clear MongoDB history, progress goals and progress photos. Continue?"
    );

    if (!confirmed) return;

    const userId = localStorage.getItem("userId");

    if (userId) {
      await fetch(`/api/client/metrics?userId=${userId}`, {
        method: "DELETE",
      });
    }

    localStorage.removeItem("clientMetricsHistory");
    localStorage.removeItem("clientStartWeight");
    localStorage.removeItem("clientGoalWeight");
    localStorage.removeItem("progressPhotos");

    window.dispatchEvent(new Event("metricsUpdated"));

    toast.success("All client progress data cleared");

    setTimeout(() => {
      window.location.reload();
    }, 700);
  };

  const downloadReport = async () => {
    try {
      const userId = localStorage.getItem("userId");

      if (!userId) {
        toast.error("User not connected");
        return;
      }

      toast.loading("Generating report...", { id: "report" });

      const res = await fetch(`/api/client/metrics?userId=${userId}`);
      const data = await res.json();

      if (!data.success) {
        toast.error("Failed to load MongoDB data", { id: "report" });
        return;
      }

      const metrics = data.data || [];

      const name = localStorage.getItem("clientName") || "User";
      const email = localStorage.getItem("clientEmail") || localStorage.getItem("email") || "client@gmail.com";
      const goal = localStorage.getItem("clientGoal") || "Maintain";
      const activity = localStorage.getItem("clientActivity") || "Moderate";

      const latest = metrics.length > 0 ? metrics[metrics.length - 1] : null;

      const historyText =
        metrics.length === 0
          ? "No metrics saved yet."
          : metrics
              .map((item: any, index: number) => {
                return `
Entry #${index + 1}
Date: ${item.date}
Weight: ${item.weight} kg
Height: ${item.height} cm
BMI: ${item.bmi}
Calories: ${item.calories} kcal
Goal: ${item.goal}
Activity: ${item.activity}
------------------------------`;
              })
              .join("\n");

      const reportContent = `
ATHLETEOS CLIENT REPORT
========================

Client Information
------------------
Name: ${name}
Email: ${email}
User ID: ${userId}
Goal: ${goal}
Activity Level: ${activity}

Latest Metrics
--------------
Weight: ${latest ? latest.weight + " kg" : "Not set"}
Height: ${latest ? latest.height + " cm" : "Not set"}
BMI: ${latest ? latest.bmi : "Not set"}
Calories: ${latest ? latest.calories + " kcal/day" : "Not set"}
Date: ${latest ? latest.date : "Not set"}

MongoDB Measurement History
---------------------------
${historyText}

Generated by AthleteOS
`;

      const blob = new Blob([reportContent], { type: "text/plain" });
      const url = URL.createObjectURL(blob);

      const link = document.createElement("a");
      link.href = url;
      link.download = "athleteos-client-report.txt";
      link.click();

      URL.revokeObjectURL(url);

      toast.success("MongoDB report downloaded", { id: "report" });
    } catch (error) {
      console.log("DOWNLOAD REPORT ERROR:", error);
      toast.error("Report generation failed", { id: "report" });
    }
  };

  const goToHistory = () => {
    const section = document.getElementById("history-section");

    if (section) {
      section.scrollIntoView({ behavior: "smooth" });
      toast.success("History section opened");
    } else {
      toast.error("History section not found");
    }
  };

  return (
    <div className="premium-card">

      <div className="mb-5">
        <h2 className="text-xl font-bold">
          Quick Actions
        </h2>

        <p className="text-gray-400 text-sm">
          Manage your MongoDB progress, history, photos and reports quickly.
        </p>
      </div>

      <div className="action-grid">

        <button
          onClick={() => {
            window.scrollTo({ top: 0, behavior: "smooth" });
            toast.success("Metrics section opened");
          }}
          className="btn-premium bg-blue-500 hover:bg-blue-400 text-white px-4 py-3 rounded-xl"
        >
          Update Metrics
        </button>

        <button
          onClick={goToHistory}
          className="btn-premium bg-gray-800 hover:bg-gray-700 text-white px-4 py-3 rounded-xl"
        >
          View History
        </button>

        <button
          onClick={downloadReport}
          className="btn-premium bg-green-500 hover:bg-green-400 text-black px-4 py-3 rounded-xl"
        >
          Download Report
        </button>

        <button
          onClick={resetProgress}
          className="btn-premium bg-yellow-500 hover:bg-yellow-400 text-black px-4 py-3 rounded-xl"
        >
          Reset Progress
        </button>

        <button
          onClick={clearHistory}
          className="btn-premium bg-orange-500 hover:bg-orange-400 text-black px-4 py-3 rounded-xl"
        >
          Clear History
        </button>

        <button
          onClick={clearPhotos}
          className="btn-premium bg-purple-500 hover:bg-purple-400 text-black px-4 py-3 rounded-xl"
        >
          Clear Photos
        </button>

        <button
          onClick={clearAll}
          className="btn-premium bg-red-500 hover:bg-red-400 text-white px-4 py-3 rounded-xl"
        >
          Clear All
        </button>

      </div>

    </div>
  );
}





